#!/usr/bin/python3

# License GPL 2. Copyright Paul D. Gilbert, 2017

# need  export PYTHONPATH=/path/to/Vcourse/lib

import time
import logging
import LED_piZeroW   as LEDs 

LEDs.off('lights out')

LEDs.systemProblem('blue')  # blue
time.sleep(1)
LEDs.off('lights out')

LEDs.warn('blink red')           # blink red
time.sleep(1)
LEDs.off('lights out')

LEDs.center('blink green')         # blink green
time.sleep(1)
LEDs.off('lights out')
