#!/usr/bin/python3

# License GPL 2. Copyright Paul D. Gilbert, 2017

# need  export PYTHONPATH=/path/to/Vcourse/lib

import time
import LEDs 

LEDs.off('lights out')

LEDs.systemProblem('blue')
time.sleep(1)
LEDs.off('lights out')

LEDs.warn('blink red')         
time.sleep(1)
LEDs.off('lights out')

LEDs.center('blink green')        
time.sleep(1)
LEDs.off('lights out')

# LEDs.update('blink red and green for 20 sec')         
# should go out itself after 20 sec

# LEDs.cleanup('clean up for shutdown')

# simulation does a lot of off at the end?
