#!/usr/bin/python3
# License GPL 2. Copyright Paul D. Gilbert, 2018
"""
Run at registration desk to find gizmo (flash LEDs), load BTconfig, and distribute.

This program needs a setting to find other modules, e.g.
   export PYTHONPATH=/path/to/Vcourse/lib

Other configuration can also be done with this utility, but might typically be
done before registration. It does

  -Boat specific configuration for the gizmo ("FLEET" and "BT_ID" ).
  -RC specific configuration ("RC_PORT" and "RC_IP").
  -GPS harware specific configuration  is written to GPSconfig.
"""
import tkinter
import signal
import logging
import json
import sys # just for exit
import os  # just for mkdir

from GUIutils import *
from CallOut import CallOut

logFormat ='(%(threadName)-9s) %(message)s'
logging.basicConfig(level=logging.DEBUG, format=logFormat,)
#logging.basicConfig(level=logging.INFO, format=logFormat,)


if __name__ == '__main__':
   
   # This uses the same files and file structure as RC for FLEETS/*/BoatList.txt
   #  but fleetList.txt is different. It has fleet RC_IP and RC_PORT info.
   # There is a comparable dict structure (there is boatLists and checkedOut for each fleet).
   #  fleets will have a sub-dict for each fleet with boatList and checkedOut, 
   #  eg: fleets = {'FX': {'BoatList': ('FX 1',), 'checkedOut': None}}

   def checkedOutList(): 
      fl = fleetChoice.get()
      return fleets[fl]['checkedOut']
       
   def readBoatList(fl, w=None):
      global fleets
      if w is not None: w.destroy()
      
      try : 
         with open('FLEETS/' +fl + '/BoatList.txt') as f: bl = f.read().splitlines()
         bl = [b.strip() for b in bl]
      except :
         bl = None   
      
      logging.debug('BoatList = bl is ' + str(bl))
      fleets[fl].update({'BoatList':bl})

   def readWindow(w=None):
      global fl, bt, RC_IP, RC_PORT, host
      if w is not None: w.destroy()
      
      fl   = fleetChoice.get()
      bt   = str(ents[0].get())
      chg  = str(ents[1].get()) 
      host = gizmoChoice.get()

   def writeFleet(w=None):
      if w is not None: w.destroy() 
      
      # THIS SHOULD ALSO INDICATE CHECKOUT STATUS
      
      fl      = fleetChoice.get()
      
      BoatList =  fleets[fl]['BoatList']
      
      # checkedOut   = 
      
      t = tkinter.Toplevel(w)
      t.wm_title(fl + "Checked Out Status")
      
      if  BoatList is None : 
         bl = 'boat list not available.'
      else :
         bl = ''
      
      if (BoatList is not None) : 
         for f in BoatList :
            #if f not in  revd : ROW(t, text='*** ' + f, pad=2)
            ROW(t, text='*** ' + f, pad=2)

   def showRC(t=None): 
      if t is not None: t.destroy()

      w = tkinter.Toplevel()
      w.wm_title(fl + "Fleet Types & RC settings")
      for d in fleetList:
         rc = str({x: fleets[d][x] for x in ('RC_IP', 'RC_PORT')})
         ROW(w, text=d + '  ' + str(rc), pad=2, width=40)
   
   def setRC(t=None): 
      # This is to all by UDP !!
      if t is not None: t.destroy()

      fl =  fleetChoice.get()
      rc = str({x: fleets[fl][x] for x in ('RC_IP', 'RC_PORT')})
      request = "setRC::" + fl + "::" + rc
      logging.debug(request)
      (bt, btADDR, conf) = CallOut("all", request, timeout=20)

   def setBTconfig(t=None): 
      # This is a complete reset of a gizmo by UDP !!
      # callout will be to a gizmo hostname (BT-#)
      # Could allow boat ID (sail #) but that may get changed by the BTconfig,
      # which would get confusing. Gizmo hostname will not change

      if t is not None: t.destroy()

      fl =  fleetChoice.get()
      hn =  gizmoChoice.get()

      rc = {'BT_ID': bt, 'FLEET': fl, 'RC_IP': fleets[fl]['RC_IP'], 'RC_PORT': fleets[fl]['RC_PORT'] }
      request = "setBTconfig::" + str(rc)
      logging.debug(request)
      
      (bt, btADDR, conf) = CallOut(hn, request, timeout=20)
      # ALSO NEED TO CHANGE fleets[] BoatList ...

      fl = conf['FLEET']
      fleetChoice.set(conf['FLEET'])

      ents[0].delete(0, tkinter.END)
      ents[0].insert(15, conf['BT_ID'])

      gizmoChoice.set(conf['hn']) 

   def newBoatSetBTconfig(bt, fl, t=None):
      if t is not None: t.destroy()

      ents[0].insert(15, bt)
      fleetChoice.set(fl)

      hn =  'BT-xx'                 # AUTO SELECT FROM UNASSIGNED LIST
      gizmoChoice.set(hn)
      # NEED TO DO DATA MANAGEMENT OF fleets...

   def callForHostG(callout, request, t=None):
      if t is not None: t.destroy()
      ents[0].delete(0, tkinter.END)  #unset sail# and fleet for case nothing is returned
      fleetChoice.set('unknown')
      callForHost(callout, request) 
 
   def callForHost(callout, request): 
      #callout can be gizmone hostname (BT-#)  or boat ID (sail #)
      global bt, btADDR
      bt = ents[0].get()
      (bt, btADDR, conf) = CallOut(callout, request)
      
      fl = conf['FLEET']
      fleetChoice.set(fl)

      ents[0].delete(0, tkinter.END)
      ents[0].insert(15, bt)
      
      #logging.debug('fleets')
      #logging.debug(fleets)
       
      fIP = fleets[fl]['RC_IP']
      fPT = fleets[fl]['RC_PORT']
      bIP = conf['RC_IP']
      bPT = conf['RC_PORT']

      if fIP != bIP  or  fPT != bPT :
         tkWarning("Boat's IP/PORT not set to fleet values! It with be reset.\n" +
                   "fleet: " + fIP + ":" + fPT + ". boat: " + bIP + ":" + bPT + ".\n" +
                   "If the boat values are correct then reset the fleet values.", width=45)

      # hn is not a standard part of BTconfig, it was added by CallOutRespond()
      gizmoChoice.set(conf['hn']) 

   def selectGizmo(): 
      hn = gizmoChoice.set(selectGizmoChoice.get())

   ##################  initiate from files    ################

   try :
      with open('FleetList.txt','r') as f: fleets =  json.load(f)
   except :
      fleets = {'No fleet': None}
   
   fleetList = tuple(fleets.keys())  # POSSIBLY SORT FOR CONSISTENT ORDER
   
   logging.debug('fleetList:')
   logging.debug(fleetList)
   
   if not os.path.exists('FLEETS'):  os.makedirs('FLEETS')

   try : 
      with open("gizmoList.txt") as f:  gizmoList =  f.read().splitlines()
      gizmoList = [b.strip() for b in gizmoList]
   except :
      gizmoList = ('No gizmos',) 
   
   #logging.debug('gizmoList:')
   #logging.debug(gizmoList)


   for d in fleetList:
      #ZEROING CHECKEDOUT MAY BE A PROBLEM
      fleets[d].update({'BoatList':(), 'checkedOut':None})
      readBoatList(d) 

   logging.debug('fleets:')
   logging.debug(fleets)

   #logging.debug('fleets[FX][RC_IP]')
   #logging.debug(fleets['FX']['RC_IP'])

   # should write BoatList file if there are changes
   
   ##################  Registration  Main  GUI     ################
   w = tkinter.Tk()

   w.wm_title("Gizmo Registration")
   w.bind('<Return>', (lambda event : readWindow()))   
   w.bind('<FocusOut>', (lambda event : readWindow()))   
   
   ents = []

   row = tkinter.Frame(w)
   ents.append(ENTRY(row, text=  'Sail #'))
   fleetChoice = DROP(row, text= ' fleet:',  options=fleetList, default = 0) #, command = changeFleet)
   But(row, text='fleet\nboat list',     command=(lambda : writeFleet()))
   row.pack(side=tkinter.TOP, fill=tkinter.X, padx=5, pady=5)
 
   row = tkinter.Frame(w)
   But(row,  text='Call Out\nBoat',      command=(lambda : callForHost(ents[0].get(), "flash, send address and BTconfig")))
   But(row,  text='Check Out\nGizmo',    command=(lambda : CallOut(ents[0].get(), "flash and send address")))
   But(row,  text='Check In\nGizmo',     command=(lambda : CallOut(ents[0].get(), "flash and send address")))
   row.pack(side=tkinter.TOP, fill=tkinter.X, padx=5, pady=5)

   row = tkinter.Frame(w)
   ents.append(ENTRY(row, text=  'Change Sail #'))
   gizmoChoice       = DROP(row, text='Gizmo ID:',       options=gizmoList,     default = 0) #, command= (lambda event : changeGizmo()))
   row.pack(side=tkinter.TOP, fill=tkinter.X, padx=5, pady=5)

   row = tkinter.Frame(w)
   But(row,  text="Commit changes\nto Gizmo",  command=(lambda : setBTconfig()))
   But(row, text='New Boat',          command=(lambda : newBoatWindow()))
   But(row, text='extra',                command=(lambda : extraWindow()))
   row.pack(side=tkinter.TOP, fill=tkinter.X, padx=5, pady=5)

   ##########   Registration New Boat  Window   ########### 

   def newBoatWindow():
      global Nents
      t = tkinter.Toplevel()
      t.wm_title("New Boat")

      Nents = []
      row = tkinter.Frame(t)
      Nents.append(ENTRY(row, text=  'New Boat Sail #'))
      NfleetChoice = DROP(row, text= ' fleet:',  options=fleetList, default = 0) #, command = changeFleet)
      row.pack(side=tkinter.TOP, fill=tkinter.X, padx=5, pady=5)

      row = tkinter.Frame(t)
      But(row,  text="Commit changes\nto Gizmo",  
                     command=(lambda : newBoatSetBTconfig(Nents[0].get(), NfleetChoice.get(), t)))
      row.pack(side=tkinter.TOP, fill=tkinter.X, padx=5, pady=5)

   ##########   Registration Extra  Window   ########### 

   def extraWindow():
      t = tkinter.Toplevel()
      t.wm_title("Extra Options")

      row = tkinter.Frame(t)
      But(row,  text="Show fleets'\nRC settings",   command=(lambda : showRC(t)) )
      But(row,  text="Propogate\nfleet's RC",       command=(lambda : setRC(t)) )
      #But(row,  text='Re-read\nlist of fleets') NEED DYNAMIC DROP MENU FOR THIS
      But(row,  text='Re-read\nBoatList')
      selectGizmoChoice = DROP(row, text='unassigned\nGizmos:', options=('None yet',), default = 0, command= (lambda event : selectGizmo()))
      But(row,  text='Call Out\nGizmo',  command=(lambda : callForHostG(gizmoChoice.get(),
                                               "flash, send address and BTconfig", t)))
      row.pack(side=tkinter.TOP, fill=tkinter.X, padx=5, pady=5)

   ###############  end  Registration  Main  GUI     ###############


   def abortHandler(signum, frame):
       logging.info('main thread exit via abortHandler.')
       sys.exit("RC process killed.")

   # ^C works if process is not deamonized with &
   signal.signal(signal.SIGINT,  abortHandler) # ^C, kill -2
   signal.signal(signal.SIGTERM, abortHandler) # kill -15 (default)

   w.mainloop()

   logging.info('main thread exit via end.')
